### ISSUE TITLE
Error cover art and game title

### ISSUE THREAD

**Issue by ranckinuta** [ktnrg45/pyps4-homeassistant#13]
I play the game named "Shadow of the Colossus" but it display "Middle-earth™: Shadow of War™"

Your Country: Taiwan
media_title: Middle-earth™: Shadow of War™
media_content_id: CUSA08804

**Comment by vmanuel** [comment]
I updated to HA 0.93.1 abd Fornite cover is not shown.
media_title: Fortnite
media_content_id: CUSA07669
Country: Spain

**Comment by JesseWebDotCom** [comment]
Also upgraded to 0.93.1 and now Last of Us cover is not shown:
media_content_id: CUSA00552
media_content_type: game
media_title: The Last of Us™ Remastered
source: The Last of Us™ Remastered
source_list: The Last Of Us™ Remastered 
friendly_name: PlayStation 4
icon: mdi:playstation
supported_features: 6528

Country: US

**Comment by ktnrg45** [comment]
> Also upgraded to 0.93.1 and now Last of Us cover is not shown:
> media_content_id: CUSA00552
> media_content_type: game
> media_title: The Last of Us™ Remastered
> source: The Last of Us™ Remastered
> source_list: The Last Of Us™ Remastered
> friendly_name: PlayStation 4
> icon: mdi:playstation
> supported_features: 6528
> 
> Country: US

Got the below results from test script:
DEBUG:pyps4_homeassistant.ps4:Found Title: The Last Of Us™ Remastered , URL: https://store.playstation.com/store/api/chihiro/00_09_000/container/US/en/19/UP9000-CUSA00552_00-THELASTOFUS00000/1557247301000/image

Seems correct. This is the data that would be used. Perhaps the query timed out.

**Comment by ktnrg45** [comment]
> I play the game named "Shadow of the Colossus" but it display "Middle-earth™: Shadow of War™"
> 
> Your Country: Taiwan
> media_title: Middle-earth™: Shadow of War™
> media_content_id: CUSA08804

Got data from test:
DEBUG:pyps4_homeassistant.ps4:Found Title: Shadow of the Colossus™, URL: https://store.playstation.com/store/api/chihiro/00_09_000/container/TW/en/19/HP9000-CUSA08804_00-SOTC0000000000AS/1558084347000/image

Not sure of how you are getting the wrong information.

**Comment by ktnrg45** [comment]
> I updated to HA 0.93.1 abd Fornite cover is not shown.
> media_title: Fortnite
> media_content_id: CUSA07669
> Country: Spain

Found issue. Thanks.
