### ISSUE TITLE
PS4 is removed after HA restart.

### ISSUE THREAD

**Issue by hwikene** [ktnrg45/pyps4-homeassistant#14]
Hi!
If i turn PS4 ccompletely "off" and restart HA i need to add the component once more from the start. Is this a bug or is there mabey something wrong with my setup?

Its all good if i put PS4 in sleep mode but i have kids and sometimes they turn PS4 "off". :)

**Comment by ktnrg45** [comment]
This is an issue with Home Assistant. Fix is in progress.
