### ISSUE TITLE
Games with no cover art

### ISSUE THREAD

**Issue by Kvasenok** [ktnrg45/pyps4-homeassistant#2]
Hera is the list of my games with no cover art. 
R5, Russia.

media_title: Overwatch: Origins Edition
media_content_id: CUSA03975

media_title: Marvel's Spider-Man
media_content_id: CUSA11995

media_title: For Honor
media_content_id: CUSA05265

**Comment by SeanPM5** [comment]
Noticed these missing as well in R1 / USA.

media_content_id: CUSA00575 
media_title: inFAMOUS First Light™

media_content_id: CUSA01623
media_title: God of War® III Remastered

media_content_id: CUSA04459
media_title: WATCH_DOGS® 2

**Comment by keredoc** [comment]
Thanks in advance for paying attention to these!

media_content_id: CUSA03220
media_title: Gran TurismoSPORT

**Comment by e-krebs** [comment]
Region R2 / western europe

media_content_id: CUSA11993
media_title: Marvel's Spider-Man

media_content_id: CUSA01073
media_title: Ratchet & Clank™

thx in advance

**Comment by ktnrg45** [comment]
Working on these. This title however I cannot find in the playstation store. 

> 
Overwatch: Origins Edition
> 
Just to confirm, this is the exact title shown in the ps4 entity in Home Assistant? @Kvasenok 
There is a Overwatch: Legendary Edition however.

**Comment by Kvasenok** [comment]
> Working on these. This title however I cannot find in the playstation store.
> 
> > 
> 
> Overwatch: Origins Edition
> 
> > 
> 
> Just to confirm, this is the exact title shown in the ps4 entity in Home Assistant? @Kvasenok
> There is a Overwatch: Legendary Edition however.

Yes, I can confirm that this is the exact title. 
![Screenshot_20190311-212216_Chrome](https://user-images.githubusercontent.com/44749170/54148171-cd0a9b00-4444-11e9-8eb1-a18999810666.jpg)
But Overwatch: Legendary Edition is still Overwatch, so if it's possible to somehow link the cover art from one to another, it should do just fine.

**Comment by ktnrg45** [comment]
> > Working on these. This title however I cannot find in the playstation store.
> > > 
> > 
> > 
> > Overwatch: Origins Edition
> > > 
> > 
> > 
> > Just to confirm, this is the exact title shown in the ps4 entity in Home Assistant? @Kvasenok
> > There is a Overwatch: Legendary Edition however.
> 
> Yes, I can confirm that this is the exact title.
> ![Screenshot_20190311-212216_Chrome](https://user-images.githubusercontent.com/44749170/54148171-cd0a9b00-4444-11e9-8eb1-a18999810666.jpg)
> But Overwatch: Legendary Edition is still Overwatch, so if it's possible to somehow link the cover art from one to another, it should do just fine.

Ok great! I'll see if I can do that.

**Comment by thundergreen** [comment]
I have this issue with R2

```
{
  "media_content_id": "CUSA01073",
  "media_content_type": "music",
  "media_title": "Ratchet & Clank™",
  "source": "Ratchet & Clank™",
  "source_list": [
    "Call of Duty®",
    "Ratchet & Clank™"
  ],
  "friendly_name": "PlayStation 4",
  "icon": "mdi:playstation",
  "supported_features": 6528
}
```

**Comment by ktnrg45** [comment]
> Noticed these missing as well in R1 / USA.
> 
> media_content_id: CUSA00575
> media_title: inFAMOUS First Light™
> 
> media_content_id: CUSA01623
> media_title: God of War® III Remastered
> 
> media_content_id: CUSA04459
> media_title: WATCH_DOGS® 2

Tested and working! Will update library when I fix the others.

**Comment by ktnrg45** [comment]
All titles listed returns correct cover with updated code will release updated pypi library shortly.
