### ISSUE TITLE
Feature request: Support for starting a title after starting the ps4

### ISSUE THREAD

**Issue by Appyx** [ktnrg45/pyps4-homeassistant#20]
I want to start a title with an automation. But in order to use source selection, I need to start the ps4 first. To combine both commands a static delay is necessary, which is unreliable.

A solution could be to buffer all requests after receiving the start command.

**Comment by ktnrg45** [comment]
This is a Home Assistant issue.  You can try adding 2 automations which are tied to a switch: One for turning on and the other to select source.

**Comment by Appyx** [comment]
PS4-waker implements this feature. Why would that be a HA issue?

**Comment by ktnrg45** [comment]
Well not an HA issue. But I think that it is better to handle that on the HA side since I believe that HA doesn't allow for selecting a source if media_player is off anyway. The GUI doesn't give any way to select source if the ps4 is off anyways, Im assuming this based on that but Ill see what I can do.

**Comment by ktnrg45** [comment]
Update for this. HA does allow to call the select_source service when it is off. Your buffering idea does seem like the way to go if I can find an good way to do this. For now you can use a script like below to improve reliability. You may have to tweak the "delay" option.

script:
  select_source:
    sequence:
      - service: media_player.turn_on
        entity_id: media_player.playstation_4
      - wait_template: "{{ is_state('media_player.playstation_4', 'idle') or is_state('media_player.playstation_4', 'playing') }}"
      - delay: '00:00:10'
      - service: media_player.select_source
        data:
          entity_id: media_player.playstation_4
          source: <source>

**Comment by ktnrg45** [comment]
Added support for this.

**Comment by Appyx** [comment]
Wow, that was fast. Thx :)
