### ISSUE TITLE
No cover art for Dark Souls III: The Fire Fades Edition in the USA

### ISSUE THREAD

**Issue by alexander-bauer** [ktnrg45/pyps4-homeassistant#23]
Hello! I'd like to report that my PS4 media player does not report cover art when playing Dark Souls III: The Fire Fades Edition. I'm in the USA region, and the `media_player` reports the following attributes:

```
media_content_id: CUSA08155
media_title: DARK SOULS™ III: The Fire Fades™ Edition
source: DARK SOULS™ III: The Fire Fades™ Edition
source_list: DARK SOULS™ III: The Fire Fades™ Edition,Terraria: PS4™ Edition
friendly_name: PlayStation 4
icon: mdi:playstation
supported_features: 6529
```

**Comment by ktnrg45** [comment]
Seems to be a rare occurrence where the SKU ID is different between base edition and re-released edition. I could not find this title on the Playstation store. Closing.
