### ISSUE TITLE
[COVER ART]

### ISSUE THREAD

**Issue by cylonr** [ktnrg45/pyps4-homeassistant#26]
**Media Data**
Please post the exact information which is shown from running the module:

**Title of Media**: Battlefield 5

**Region**: Portugal

**Comment by ktnrg45** [comment]
`DEBUG:pyps4_2ndscreen.ps4:Found Title: Battlefield™ V, URL: https://store.playstation.com/store/api/chihiro/00_09_000/container/PT/pt/19/EP0006-CUSA08670_00-BATTLEFIELDV0000/1572448767000/image`

Tests found title. The region of your game may be different.
