### ISSUE TITLE
[COVER ART]

### ISSUE THREAD

**Issue by Geoff571** [ktnrg45/pyps4-homeassistant#29]
**Media Data**
media_content_id: CUSA01780
media_title: Spotify

**Title of Media**: "Spotify"
**SKU ID**: eg. "CUSA01780"

Cover Art not displayed
`Could not find data in region: United Kingdom for PS ID: CUSA01780`

Also post the region your are using in the module.
**Region**: eg. "United Kingdom

**Comment by ktnrg45** [comment]
Unfortunately it seems this app cannot be found by search engine on the PlayStation Store website. However since it is a system included app I would have to pin the image URL.

**Comment by Geoff571** [comment]
Is there anyway to configure the component to use a local store for images? I know the original pre-release version had that option and I still have the local images

**Comment by ktnrg45** [comment]
Yes there is. If you open the .ps4-games.json file you should see something like:
```
{
    "CUSA01780": {
        "locked": false,
        "media_content_type": "null",
        "media_image_url": "null",
        "media_title": "Spotify"
    }
}
```

Change the entry to some thing like this:

```
{
    "CUSA01780": {
        "locked": true,
        "media_content_type": "app",
        "media_image_url": "https://store.playstation.com/store/api/chihiro/00_09_000/container/us/en/999/EP4950-CUSA01780_00-US00000000000000/1559667794000/image",
        "media_title": "Spotify"
    }
}
```

If you want to use a local image, place the image in your config/www directory and  change the value of `media_image_url` to `http://localhost:8123/local/image.jpg`.

**Comment by ktnrg45** [comment]
Let me know if you have issues with that. I'll close this issue since now Spotify is pinned.
