### ISSUE TITLE
Feature request: make UDP port configurable

### ISSUE THREAD

**Issue by mvn23** [ktnrg45/pyps4-homeassistant#33]
**Is your feature request related to a problem? Please describe.**
The UDP port (not the DDP port) is selected at random on each initialization of the library. This is not very firewall-friendly.

**Describe the solution you'd like**
Make the UDP port configurable.

**Describe alternatives you've considered**
Open the firewall for all UDP traffic from the PS4. This is what I'm currently doing, but it's not a very clean solution.

**Additional context**
N/A

**Comment by ktnrg45** [comment]
Hello. That's a pretty good idea. I'm assuming the use case is for Home-Assistant?

**Comment by ktnrg45** [comment]
Do you have issues with the TCP port at all? The DDP port is a broadcast socket. The UDP port for credentials service is the other UDP port which needs to be 987. The TCP port is for connections(Turning off, remote control).

**Comment by mvn23** [comment]
> Hello. That's a pretty good idea. I'm assuming the use case is for Home-Assistant?

Indeed it is. However I saw that it isn't possible with the library at the moment, so I requested it here at first.

> Do you have issues with the TCP port at all? The DDP port is a broadcast socket. The UDP port for credentials service is the other UDP port which needs to be 987. The TCP port is for connections(Turning off, remote control).

From what I understand, UDP 987 is fixed (as in, it won't work on a different port).
The other UDP port ([this one](https://github.com/ktnrg45/pyps4-2ndscreen/blob/5f0ad2a92f07e3adb14eda860b467b84573d9b5a/pyps4_2ndscreen/ddp.py#L15)) is variable and could be made configurable.
If the TCP port is not required to be on a specific port then it would make sense to make this configurable as well, but I did not encounter any issues with it so far.
Just for clarity, is the TCP port only used for outgoing connections? Or are there scenarios where this will be a listening socket?

**Comment by ktnrg45** [comment]
Ok so we do want to configure the DDP port then (status messages)? There are two versions of this (Async and socket.socket). The Asyncio protocol sends and receives messages directly to/from the PS4 987 port (not using broadcast though, I forgot that there would be issues with VLANs). But we definitely can make the local port configurable.

You are correct. The local TCP port is outgoing and can be any port, the destination/PS4 port must be 997. We are solely the client in this instance and do not listen for connections; the PS4 is the host/server.

**Comment by mvn23** [comment]
> Ok so we do want to configure the DDP port then (status messages)?

Indeed. The reason I stated `(not the DDP port)` in the opening post is that the source refers to UDP 987 as `DDP_PORT`.

> You are correct. The local TCP port is outgoing and can be any port, the destination/PS4 port must be 997. We are solely the client in this instance and do not listen for connections; the PS4 is the host/server.

Thanks for the info, I will close this one again in my firewall config.

**Comment by ktnrg45** [comment]
Ok I see. I'll implement this here then in Home Assistant later.

**Comment by ktnrg45** [comment]
Functionality is present in library now. Will need to integrate with HA.
