### ISSUE TITLE
[COVER ART]

### ISSUE THREAD

**Issue by Pippo76** [ktnrg45/pyps4-homeassistant#34]
**Media Data**
Please post the exact information shown from running the module:
Also note if cover art is not found or is incorrect.
Symbols in the title are important, don't forget to include them.

**Title of Media**: eg. "Call of Duty™"

**SKU ID**: eg. "CUSA15277"

**Region**: eg. "Suisse"

Merci.

**Comment by Shkrum31** [comment]
As requested:

Title of Media: "Diablo III: Reaper of Souls - Ultimate Evil Edition™"
SKU ID: "CUSA00433"
Region: "France"



Manually corrected the following

>     "CUSA00433": {
>         "locked": false,
>         "media_content_type": null,
>         "media_image_url": null,
>         "media_title": "Diablo III: Reaper of Souls \u2013 Ultimate Evil Edition"
>     },

by

>     "CUSA00433": {
>         "locked": true,
>         "media_content_type": "game",
>         "media_image_url": "https://store.playstation.com/store/api/chihiro/00_09_000/container/FR/fr/999/EP0002-NPEB02026_00-D3ULTIMATEEVIL00/1579310208000/image",
>         "media_title": "Diablo III: Reaper of Souls \u2013 Ultimate Evil Edition"
>     },

Thanks

**Comment by ktnrg45** [comment]
Thanks. Should be fixed now.
