### ISSUE TITLE
Why no Ukraine?

### ISSUE THREAD

**Issue by sweetpalma** [ktnrg45/pyps4-homeassistant#35]
**Developing or Using?**
I am using this as a Home Assistant integration. So why no Ukraine database? Is there any way I could help?

**Comment by ktnrg45** [comment]
Hello, thanks for offering to help. I had trouble figuring out how to search Ukraine's PlayStation Store at first. I re-looked into it and figured it out. So hopefully this should make it into Home Assistant soon!
