### ISSUE TITLE
[Cover Art] Different apps and games 

### ISSUE THREAD

**Issue by onunomendonca** [ktnrg45/pyps4-homeassistant#37]
CUSA00127:  "media_title": "Netflix"
CUSA07319:  "media_title": "Horizon Zero Dawn\u2122"
CUSA07669:  "media_title": "Fortnite"
CUSA00512:  "media_title": "Beyond: Two Souls\u2122"
Region: Portugal

**Comment by onunomendonca** [comment]
Also fortnite in Portugal:

CUSA07669": {
        "locked": false,
        "media_content_type": null,
        "media_image_url": null,
        "media_title": "Fortnite"

**Comment by onunomendonca** [comment]
Also Beyond two souls:

CUSA00512": {
        "media_title": "Beyond: Two Souls\u2122"

**Comment by onunomendonca** [comment]
If you want me to help you i can give you the photos i'm using! :=)

**Comment by ktnrg45** [comment]
Sure thing! I actually need a good url for Playstation Now, so if you have that it would be great. All of these should be fixed soon except ` CUSA07319: "media_title": "Horizon Zero Dawn\u2122"`
This seems to be a different region than Portugal.
