### ISSUE TITLE
[COVER ART]

### ISSUE THREAD

**Issue by chatainsim** [ktnrg45/pyps4-homeassistant#38]
**Media Data**
cover art not fund
Game
media_content_id: CUSA11095
media_title: Paw Patrol: En Mission !
source: Paw Patrol: En Mission !

**Region**: "France"

**Comment by ktnrg45** [comment]
Hi. Unfortunately I cannot fix this issue. On the PlayStation Store it seems that they bundled this title and removed the individual listing.
