### ISSUE TITLE
[COVER ART]

### ISSUE THREAD

**Issue by fredrikbuchanan** [ktnrg45/pyps4-homeassistant#39]
**Media Data**
cover art and content type not found
**Title of Media**: eg. "Fallout 4"

**SKU ID**: eg. "CUSA02962"

**Region**: eg. "Europe"

    "CUSA02962": {
        "locked": false,
        "media_content_type": null,,
        "media_image_url": null,
        "media_title": "Fallout 4"

**Comment by ktnrg45** [comment]
What country are you using?

**Comment by fredrikbuchanan** [comment]
Sweden

**Comment by ktnrg45** [comment]
Ok thanks. It seems that the game you are using is not in the correct region. The sku id would be CUSA02557.
