### ISSUE TITLE
The source shows nothing after pairing

### ISSUE THREAD

**Issue by tongt15** [ktnrg45/pyps4-homeassistant#4]
Hi ktnrg45

Thanks for your work first,  however, there is no options in source, so I just can use ps4 intergration for power on and power off. Region Hong Kong, I don't know how to save the log for ps4, if you need, please tell me. Thank you!

**Comment by tongt15** [comment]
Running: Hass.io (ESXI, vmdk)

**Comment by ktnrg45** [comment]
The integration saves the title to the source list if your PS4 is currently running that title. You must start the title first by another method like a controller.
