### ISSUE TITLE
Discovery doesnt work on firewall locked down systems... resolution is included

### ISSUE THREAD

**Issue by KiwiLostInMelb** [ktnrg45/pyps4-homeassistant#40]
**External Application?**
Via CLI

**Describe the bug**
When the system has a firewall in place then the use of a dynamic port just work work.

**To Reproduce**
Set up a firewall and block all UDP ports except 987 and 997.  Second screen app will not see the pyps4 endpoint. Search will also fail if you already have a credentials file.

**Expected behavior**
It works lol.

**Screenshots**
NA

**Desktop (please complete the following information):**
Fedora 32

**Smartphone (please complete the following information):**
NA - but I use android for second screen app

**Additional context**
First off - thanks so much for porting this.  Great work and a great little script.

The real issue - not setting a UDP listen port for the listening socket causes it to use a random port which cannot be allowed through a firewall - UDP_PORT was set to 0

Ok, so how I fixed this....... and got it working.
I set a dedicated port for UDP_PORT so it does NOT use a dynamic port.  Note that this is an option in ps4-waker but not your version.

All changes in ddp.py only.

I used:
UDP_PORT = 997 - i.e. something close... Leaving it unset means it chooses a port most likely above 40000 which will be blocked by the firewall - found this by trolling the dmesg logs for blocked messages from my PS4 IP address.

I would suggest that you set a default for this.  0 is just to open to issues in many systems.

I also had to bind the socket in Discovery.__init__
Line 372 added as
        self.sock.bind((UDP_IP, UDP_PORT))
This forces a set UDP port to be used (previously set as 997 above).  Leaving it open uses a dynamic port which doesnt work.
I notice that you have bound the socket to UDP_PORT elsewhere but might have missed it for the search routine?

Also, there is another bug which should be fixed....

in Discovery.search

You close the socket if there is an exception (timeout) BUT not if it exits cleanly.

ADD
self.sock.close()
before the line (around line 402 ish) 
return self.ps_list
 
Because I used a port that is reused later (UDP_PORT) it caused an error as it was already in use.  Closing it cleanly fixed it for later.

Further suggestion:
Up the timeout in def receive(self) ... I found it a bit short for a flakey network.
available, _, _ = select.select([self.sock], [], [], 1) ##0.01)
You set the socket timeout to 6 seconds but still only waited for 0.01 second - maybe you meant to wait for the same time as the socket timeout (6).

So apologies for the confusion in my response as I am not a python developer (I am a microcontroller C++ developer) and there may be a much better way of doing this than I did.  I just wanted to get it going for my home assistant installation.

I would also like to suggest that you add the ability to set the UDP_IP from the command line.  I didnt need this BUT in a multi-adapter system this might cause issues. 

Feel free to contact me if needed....

KiwiLostInMelb

**Comment by ktnrg45** [comment]
Thanks for pointing out that the socket is not closed on success. I'm also going to clean up the timeout logic as it doesn't behave as expected. Thank you for pointing that out as well. 

Now for the ports. May I ask what firewall rules you are planning on using exactly?

It seems like the PS4 responds with a dynamic port always. Is this what you are seeing?  We can in fact choose the source port on the cli end. However, I don't see how this is useful for protecting the cli device, unless you are trying to protect your PS4. You would still have to allow all incoming ports for the cli device.

I see that you are using Home Assistant. You will likely have trouble with the PS4 integration as well if you are using the same firewall rules.

The address "0.0.0.0" should bind on all interfaces available if I'm not mistaken.

**Comment by KiwiLostInMelb** [comment]
You're most welcome.

Ok, so what I saw was different.  When sending via a bound socket the PS4
responded to the same socket.

I added to globals:
SEARCH_UDP_PORT = 997

So binding the socket to say 997 in discovery.init
def __init__(self):
....
        self.sock.bind((UDP_IP, SEARCH_UDP_PORT))

The PS4 responded from a dynamic socket - yes - but it responded to port
997 - which I could port forward through the firewall to the docker
instance of homeassistant. I could also lock down the src ip's to the local
network.

BTW - still havent got HomeAssistant to work correctly (trolling through
code now) but the pyps4 cli is working correctly for search now.

The issue with binding to 0.0.0.0 caused some issues with running in docker
only - I got around this by renaming my host adapter to eth0.  Ignore this
as it is purely a docker on fedora issue as fedora doesnt use eth(x) naming
- it uses enc(something) which alpine linux in docker didnt like for some
reason???

Hope this makes sense....

**Comment by KiwiLostInMelb** [comment]
Sorry forgot to add...

I am running the cli inside my homeassistant docker container not on the host - although testing the host had the same issue as it has the same firewall/rules.

What also might not have been clear is that binding the port seemed to mean that the discovery broadcast is SENT from the bind port.  The PS4 responded to the same port and host ip (masq so seen as 192.168.0.2) that sent it the message.  The PS4 did not appear to be sending to a broadcast IP (in my case broadcast should have shown as 192.168.0.255 but I saw DEST as 192.168.0.2).  

The docker container is masqeraded so it used the host adapter IP (192.168.0.2) as it send IP and the PS4 responded directly to the host IP and the port that sent the message.  The docker container has an internal IP of 172.x.x.x.x.

**Comment by KiwiLostInMelb** [comment]
Found the issue with homeassistant.....  HA overrides and more importantly clears variables somehow.  Not being a python developer I struggled with this. The fix is below and added to discovery.init
Logging in debug mode with the extra debug line below tracked it down for me.

def __init__(self):
        """Init."""
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        if SEARCH_UDP_PORT is None:
            SEARCH_UDP_PORT = 997            
        self.sock.bind((UDP_IP, SEARCH_UDP_PORT))
        _LOGGER.debug(
            "Binding discovery IP: %s Port: %d",
             UDP_IP,  SEARCH_UDP_PORT)       
        self.sock.settimeout(6.0)
....

Learning another language is a bit of a PITA but happy it is solved for me.

**Comment by ktnrg45** [comment]
Pushed changes to dev branch.  Please test if it corrects the issues (not in HA or docker). Also since the api involves broadcasts for the discovery, the host and the ps4 need to be on the same subnet/vlan/broadcast domain.

**Comment by KiwiLostInMelb** [comment]
Cloned dev and ran on command line - all ok after I opened UDP 1987.  Tested on host first and inside docker using cli.

Tested link, search, standby - all worked. 

Thanks heaps!

**Comment by KiwiLostInMelb** [comment]
BTW just checked your code - yes the timeout for the socket is set to 3 seconds BUT it seems to me that you are only waiting for 0.01 seconds for a message to become available - 
available, _, _ = select.select([sock], [], [], 0.01) <--- 0.01 seconds wait not timeout seconds.
As you are closing the socket in this routine any further messages are lost.

Maybe you meant to loop here multiple times or maybe not close the socket?

Over to you to decide if this is correct.  My understanding is a bit limited.

**Comment by ktnrg45** [comment]
So basically the select.select checks the socket if there is anything to read and will only block for 0.01 second. The socket timeout is 0 so recv calls will not block, the recv method is only called if there is data to read. If the timeout is greater than 0 than recv calls will block the entire thread for that amount of time which is not desireable. The socket is closed after the loop. The data is read in the loop.

Awesome. Thanks for testing this.

**Comment by KiwiLostInMelb** [comment]
Sorry mate, I really dont want to bug you on this and I do understand why you are using this for non-blocking BUT closing the socket after the read is my question - closing the socket immediately after will discard all other messages received.  Perhaps you meant to leave the socket open and re-poll it for the next message like you are already.

As I understand the flow is:
1 - send a request for information via broadcast
2 - have the socket receive the messages in the background (3 second timeout - cool)
3 - Poll the socket for data and process
4 - Keep polling for a time period for further messages

If the socket is closed at number 3 (which I think it is) then 4 wont work will it?  If you repeat the whole loop (1-4) then you get repeated messages of the same PS4 and no other PS4's on the network - assuming that the same PS4 always responds first.  

I just didnt understand the logic of closing the socket at point 3.... Of course feel free to ignore me if I have got this totally wrong.  Just trying to make sure that its not a bug.

**Comment by KiwiLostInMelb** [comment]
Ok, so sorry - ignore my last comment - I read the code wrong - you are not closing until after step 4.
