### ISSUE TITLE
Covert art more precise info

### ISSUE THREAD

**Issue by AKuHAK** [ktnrg45/pyps4-homeassistant#44]
**Is your feature request related to a problem? Please describe.**
There is an easier way to retrieve the game Covert Arts. As I understand now it searches game title in the store, then takes the first result and tries to resolve it into API. It seems that there is an easier way to achieve it without searching through the store.
`https://store.playstation.com
/store/api/chihiro/00_09_000/titlecontainer/[country]/[region]/999/[title_id]_00/image`
For example for 2 games that I missed covers: Mortal Kombat 11 (CUSA11379) and Worms Rumble (CUSA23465)
```
https://store.playstation.com/store/api/chihiro/00_09_000/titlecontainer/ru/ru/999/CUSA11379_00/image
https://store.playstation.com/store/api/chihiro/00_09_000/titlecontainer/ru/ru/999/CUSA23465_00/image

```
**Describe the solution you'd like**
Change API to not use web search at all.

**Comment by ktnrg45** [comment]
Awesome thanks for this. Looks promising. I'll test this later.
