### ISSUE TITLE
[COVER ART] Cyberpunk 2077

### ISSUE THREAD

**Issue by Kirbo** [ktnrg45/pyps4-homeassistant#47]
**Media Data**
```
  "CUSA18278": {
    "media_title": "Cyberpunk 2077",
    "media_image_url": null,
    "media_content_type": null,
    "locked": false
  }
```

**Title of Media**: "Cyberpunk 2077"

**SKU ID**: "CUSA18278"

**Region**: "Europe"

**Comment by ktnrg45** [comment]
> **Media Data**
> 
> ```
>   "CUSA18278": {
>     "media_title": "Cyberpunk 2077",
>     "media_image_url": null,
>     "media_content_type": null,
>     "locked": false
>   }
> ```
> 
> **Title of Media**: "Cyberpunk 2077"
> 
> **SKU ID**: "CUSA18278"
> 
> **Region**: "Europe"

Thanks for reporting this. This title has been removed from the Playstation store so it will not be found.
