### ISSUE TITLE
[COVER ART] Child of Light

### ISSUE THREAD

**Issue by Kirbo** [ktnrg45/pyps4-homeassistant#49]
**Media Data**
```
  "CUSA00074": {
    "media_title": "Child of Light",
    "media_image_url": null,
    "media_content_type": null,
    "locked": false
  }
```

**Title of Media**: "Child of Light"

**SKU ID**: "CUSA00074"

**Region**: "Europe"

**Comment by ktnrg45** [comment]
This appears to have been removed from the Playstation Store.
