### ISSUE TITLE
[COVER ART] Evolve

### ISSUE THREAD

**Issue by Kirbo** [ktnrg45/pyps4-homeassistant#52]
**Media Data**
```
  "CUSA00432": {
    "media_title": "Evolve",
    "media_image_url": null,
    "media_content_type": null,
    "locked": false
  }
```

**Title of Media**: "Evolve"

**SKU ID**: "CUSA00432"

**Region**: "Europe"

**Comment by ktnrg45** [comment]
This appears to have been removed from the Playstation Store.

**Comment by Kirbo** [comment]
Should this then rather try to find the items e.g. here: https://orbispatches.com/CUSA00432
Then you'd get the `media_image_url` and the `media_content_type`, even if the game was deleted:
- https://orbispatches.com/CUSA00432 -> Evolve
- https://orbispatches.com/CUSA23465 -> Worms Rumble
- https://orbispatches.com/CUSA00074 -> Child of Light
- https://orbispatches.com/CUSA16553 -> Cat Quest II
- https://orbispatches.com/CUSA18278 -> Cyberpunk 207
- https://orbispatches.com/CUSA16183 -> EA Access / EA Play Hub
- https://orbispatches.com/CUSA01116 -> Youtube

etc.

**Comment by Kirbo** [comment]
...or as a fallback, if the game is not found via using the current method (from/how ever it is done), then the script would fallback to try and find it from www.orbispatches.com and if it isn't found even there, then give up.

**Comment by Kirbo** [comment]
I'll create a separate task for this
