### ISSUE TITLE
Seem to have lost connection?

### ISSUE THREAD

**Issue by ProLoser** [ktnrg45/pyps4-homeassistant#6]
I can't really tell but it feels like HA has lost the connection to the PS4. Is there a simple way to debug if it's working? When I try to send commands like the `PS` button or sending `media_player.turn_on` or `turn_off` nothing seems to respond. HA is still listed as an authorized remote device, but I don't see that commands are getting received by the PS4.

Should I just delete and recreate the connection (which is a bit tedious) or is there any way to refresh/renew tokens/etc?

**Comment by ktnrg45** [comment]
Please post your HA logs for the ps4 component. That would be most helpful to debug.
